version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=sql5.freemysqlhosting.net
      - DB_DATABASE=sql5715665
      - DB_USERNAME=sql5715665
      - DB_PASSWORD=ZKSlbYLkk1
